---
title: "Statpackage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Statpackage}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
runtime: shiny
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Statpackage)
```

```{r}
#' A function for descriptive statistics
#' The first step after creating the data or reading data from an csv file is descriptive analysis.
#' This function provides the user with information such as mean, standard deviation, and etc.
#' x = rnorm (n, mean, sd)
#' y = rnorm (m, mean, sd)
#'
#' @param x vector of sample data from the population
#'
#' @return The function returns mean,median,25th and 75th quartiles,min,max
#' @export
#'
#' @examples
#' mydata(x = rnorm (20,5,10))
mydata <- function(x){
  myx <- summary(x)
  return(myx)
}
```

```{r}
#' A function to plot x, y
#' This plot, shows the distribution, mean and standard deviation of the data in seperate box plots.
#' 
#' 
#' @param x vector of sample data from population 1
#' @param y vector of sample data from population 2
#'
#' @return 2 plots, for sample one and two
#' @export
#'
#'
#' @examples
#' x = rnorm(30,10,12); y = rnorm(40,20,15); plot(x,y)
library(ggplot2)

myplot <- function(x, y){
  plot(x, type = "p", xlab = "Sample Data of population 1", col = "dark red")
  par(new=FALSE)
  plot(y, type = "p", xlab = "Sample Data of population 2", col = "dark blue")
}
```

```{r}
#' The box plot value
#' This function provides a discription of the box plot.
#'
#' @param x vector of sample data from population 1
#'
#' @return This function returns a list of 6 components:
#' n: the number of observation the boxplot is drawn with
#'
#' conf: upper/lower extremes of the notch, out-value of the outliers
#'
#' group: a vector of the same length that
#' indicate to which group the outlier belongs to.
#'
#' names: a vector of names for the groups.
#'
#'
#' @export
#'
#' @examples
#' myboxplotvalue (x)
boxvalue <- function(x){
  xvalue <- boxplot(x, type = "p", xlab = "Sample Data of population 1",
                    col = "dark red", horizontal = TRUE)

  return(xvalue)
}

```

```{r}
library(vioplot)

#' A function to create a violin plot to compare the two samples
#'
#' @param x : vector of sample data from population 1
#' @param y : vector of sample data from population 2
#'
#' @return A violin
#' @export
#'
#' @examples
violinplot <- function(x, y){
  title <- ("Violin plot of sample x and y")
  vioplot(x, y, names=c("Sample x", "Sample y"), main = title, col="gold")
}
```

```{r}
#' A function for t tests
#'
#'
#' The constructor function is based on t-test, that evaluates the NUll hypothesis H0.
#' H0 (The Null Hypothesis) claims that two populations have the same mean.
#'
#' x and y have underlying normal distribution.
#'
#' @param x vector of sample data from population 1
#' @param y vector of sample data from population 2
#'
#' @param paired TRUE or FALSE,
#' paired = FALSE by default
#' The samples are paired = TRUE, if each experimental unit is measured twice.
#' In that case the first experiments creates sample x,
#' and the second experiment creates sample y.
#' The two-sided t-test is used for paired sapmles.
#'
#' The test returns an error if the samples have different size.
#'
#' @param alpha alpha level is always between 0,1,
#' which determines the confidence interval for the P-value.
#'
#'
#' @return The test return a list containing the data, and t test object.
#' @export
#'
#' @examples
#' myttest(x = rnorm(30,10,12), y = rnorm(40, 7, 10))
myttest <- function(x, y, paired=FALSE, alpha=0.05){
  if(paired == "FALSE"){ #If the samples are not paired then use a t-test.
    vt = var.test(x,y)

    if(vt$p.value > alpha){
      tt <- t.test(x, y, var.equal = TRUE, conf.level = 1-alpha)
    }
    else{
      tt <- t.test(x, y, var.equal = FALSE, conf.level = 1-alpha)
    }
  }
  else{ #If the samples are paired then check the lengths.
    #If the lengths are different the algorithms stops.

    if (length(x) != length(y)){
      print("The sample sizes are not the same.")
    }
    if (length(x) == length(y)){
      tt <- t.test(x, y, paired=TRUE, conf.level=1-alpha, alternative = "two.sided")
    }

  }

  data = c(x,y)
  v = rep(c("x","y"), c(length(x),length(y))) # Creation of qual var
  df = data.frame(data=data, v=v)
  lst=list(ttest=tt, df=df, paired = paired)
  class(Rttest) <- "mytt" #New class
  print (Rttest)

}
```

```{r}
library(shiny)
library(ggplot2)
library(vioplot)

#Start the app
ui <- fluidPage(

  #App title
  titlePanel("Descriptive and Inferential Statistics"),

  fluidRow(
    #App inputs
    column(width = 8,
           strong("For paired T-test the sample sizes must be equal."),
           checkboxInput(inputId = "pairing", label = "Is the data paired?",
                         value = FALSE)),


    column (width = 5,
            strong("Input Sample Data: x"),
            wellPanel(

              #Slidebar for input
              sliderInput( inputId = "numx", label = "Choose the sample size:",
                           value = 25, min = 20, max = 100),

              sliderInput( inputId = "mux", label = "Choose the sample mean:",
                           value = 5, min = 0, max = 10),

              sliderInput( inputId = "sdx", label = "Choose the sample standard deviation:",
                           value = 5, min = 1, max = 20)

            ),

            strong("Input Sample Data: y"),
            wellPanel(

              #Slidebar for input
              sliderInput( inputId = "numy", label = "Choose the sample size:",
                           value = 25, min = 20, max = 100),

              sliderInput( inputId = "muy", label = "Choose the sample mean:",
                           value = 5, min = 0, max = 10),

              sliderInput( inputId = "sdy", label = "Choose the sample standard deviation:",
                           value = 5, min = 1, max = 20)
            )),
    #App outputs

    column (width = 5,
            h5("Box plot"),
            plotOutput(outputId = "boxplot1")
            ),

    column (width = 5,
            h5("Box plot"),
            plotOutput(outputId = "boxplot2")
            ),

    column (width = 5,
            h4("T-test results"),

    strong("Statistics:"),
    textOutput(outputId = "statistic"),

    strong("Parameter:"),
    textOutput(outputId = "parameter"),

    strong("P-value:"),
    textOutput(outputId = "pvalue"),

    strong("Confidence Interval:"),
    textOutput(outputId = "conf"),

    strong("Estimate:"),
    textOutput(outputId = "estimate"),

    strong("Method:"),
    textOutput(outputId = "method"),

    strong("Alternative Method:"),
    textOutput(outputId = "alternative"),

    ),

    column (width = 5,
            h5("Violin Plot"),
            plotOutput(outputId = "violin")
    )


  )

)



server <- function(input,output)
{
         output$violin <- renderPlot({
          set.seed(32)
          x = rnorm (input$numx, mean = input$mux, sd = input$sdx )
          y = rnorm (input$numy, mean = input$muy, sd = input$sdy )

          title <- ("Violin plot of sample x and y")
          vioplot(x, y, names=c("Sample x", "Sample y"), main = title, col="gold")

        })

          output$statistic <- renderText({
            set.seed(32)
            l1 = rnorm (input$numx, mean = input$mux, sd = input$sdx )
            l2 = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            t_test <- t.test(l1, l2, paired = input$pairing, alpha=0.05)

            t_test$statistic

          })

          output$parameter <- renderText({
            set.seed(32)
            l1 = rnorm (input$numx, mean = input$mux, sd = input$sdx )
            l2 = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            t_test <- t.test(l1, l2, paired = input$pairing, alpha=0.05)

            t_test$parameter

          })

          output$pvalue <- renderText({
            set.seed(32)
            l1 = rnorm (input$numx, mean = input$mux, sd = input$sdx )
            l2 = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            t_test <- t.test(l1, l2, paired = input$pairing, alpha=0.05)

            t_test$p.value

          })

          output$conf <- renderText({
            set.seed(32)
            l1 = rnorm (input$numx, mean = input$mux, sd = input$sdx )
            l2 = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            t_test <- t.test(l1, l2, paired = input$pairing, alpha=0.05)

            t_test$conf.int

          })

          output$estimate <- renderText({
            set.seed(32)
            l1 = rnorm (input$numx, mean = input$mux, sd = input$sdx )
            l2 = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            t_test <- t.test(l1, l2, paired = input$pairing, alpha=0.05)

            t_test$estimate

          })


          output$alternative <- renderText({
            set.seed(32)
            l1 = rnorm (input$numx, mean = input$mux, sd = input$sdx )
            l2 = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            t_test <- t.test(l1, l2, paired = input$pairing, alpha=0.05)

            t_test$alternative
          })

          output$method <- renderText({
            set.seed(32)
            l1 = rnorm (input$numx, mean = input$mux, sd = input$sdx )
            l2 = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            t_test <- t.test(l1, l2, paired = input$pairing, alpha=0.05)

            t_test$method
          })

          output$boxplot1 <- renderPlot({
            set.seed(32)
            x = rnorm (input$numx, mean = input$mux, sd = input$sdx )

            title <- ("Sample data of population 1")
            boxplot(x, main = title, col = "dark blue")

          })

          output$boxplot2 <- renderPlot({
            set.seed(32)
            y = rnorm (input$numy, mean = input$muy, sd = input$sdy )

            title <- ("Sample data of population 2")
            boxplot(y, main = title, col = "dark red")
          })

}


shinyApp(ui=ui, server=server)

```



